config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
  	get 'toggle_completed', on: :member
  	get 'filter_by_tag', on: :collection
  end
	root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

	before_save :remove_blank_and_duplicate_tags

	validates :title, presence: true

	def remove_blank_and_duplicate_tags
		tags.uniq!
		tags.reject!(&:blank?)
	end
	# def set_deadline_to_now
	#   self.deadline = Time.now
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def toggle_completed
    @task = Task.find(params[:id])
    @task.toggle!(:completed)
    respond_to do |format|
        format.js
    end
  end

  def filter_by_tag
    @tag = params[:tag]
    @tasks_tag = Task.where('? = ANY(tags)', @tag)
    respond_to do |format|
      format.js do
        render partial: 'table', locals: {tasks: @tasks_tag}
      end
    end
  end

  # GET /tasks
  def index
    @tasks_today = Task.where(deadline: Date.today.beginning_of_day..Date.today.end_of_day).order(:deadline)
    @tasks_today_ongoing = @tasks_today.where(completed: false).where('deadline > ?', Time.now).count

    @tasks_other = Task.where.not(deadline: Date.today.beginning_of_day..Date.today.end_of_day).or(Task.where(deadline: nil))
    @tasks_other_ongoing = Task.where.not(deadline: Date.today.beginning_of_day..Date.today.end_of_day).where("deadline > ?", DateTime.now).or(Task.where(deadline: nil)).where(completed: false).count

    @all_tags = Task.pluck(:tags).flatten.uniq

    @tasks_untagged = Task.where("tags = '{}'")

    @i = 0
    @task = Task.new


  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @all_tags = Task.pluck(:tags).flatten.uniq
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to :root, notice: 'Task was successfully created.' }
      else
        format.html { redirect_to :root, alert: 'Task was not created. <br>Reason: '+@task.errors.full_messages.join('; ') }
      end
    end
  end

  # PATCH/PUT /tasks/1
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to :root, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :completed, :deadline, :notes, tags: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def completed_link_text(model)
  	if model.completed?
  		'Completed'
  	elsif model.deadline and model.deadline.past?
  		'Overdue'
  	else
  		'On-going'
  	end
  end

  def completed_link_data_order(model)
  	if model.completed?
  		2
  	elsif model.deadline and model.deadline.past?
  		1
  	else
  		0
  	end
  end

  def pretty_print_deadline(model)

    if model.deadline
      diff = distance_of_time_in_words_to_now(model.deadline)
      if model.deadline - DateTime.now < 0
        diff + ' ago'
      else
        'in ' + diff
      end
    else
      "No deadline"
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CvwoToodoo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.13/r-2.1.0/datatables.min.css"/>


  </head>

  <body>
    <%= yield %>
  </body>

  <script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title %>
  <%= f.input :deadline, as: :datetime_picker %>
  <%= f.input :tags, as: :array, input_html: { class: 'form-control', placeholder: 'More tags...' } %>
  <%= select_tag "previous-tags", options_for_select(@all_tags, ''), {prompt: 'Quick add a tag', class: 'form-control', style: 'width: auto; margin-bottom: 20px;'} %>
  <%= f.input :notes %>

<!--   <button class="add-tag-button btn btn-default" style="margin-bottom: 25px;">Add more tags</button> -->
  <%= f.button :submit, class: 'btn btn-danger' %>

<% end %>

<style>
  li.picker-switch > table > tbody > tr > td > a[data-action="today"] > span:after {
    content: '  Go to today';
    font-family: 'Roboto';
  }

  li.picker-switch > table > tbody > tr > td > a[data-action="clear"] > span:after {
    content: '  Disable deadline';
    font-family: 'Roboto';
  }

  .task_tags label {
    display: block;
  }

  .task_tags input {
    margin-right: 10px;
    margin-bottom: 5px;
    width: 120px;
    display: inline;
  }
</style>

app/views/tasks/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Completed?</th>
      <th>Deadline</th>
      <th>Tags</th>
      <th>Actions</th>
      <th>Notes</th>
    </tr>
  </thead>

  <tbody>
    <% tasks.each do |task| %>
      <tr id="task_<%= task.id %>">
        <td><a class="show-task" data-toggle="modal" href='#modal-show-task' data-task-id="<%= task.id %>" data-task-title="<%= task.title %>"><%= task.title %></a></td>
        <td data-order="<%= completed_link_data_order(task) %>" data-search="<%= completed_link_text(task) %>">
          <% if completed_link_text(task) == 'Completed' or completed_link_text(task) == 'On-going' %>
            <%= link_to completed_link_text(task),
            toggle_completed_task_path(task),
            :remote => true, id: "completed_link_#{task.id}", class: completed_link_text(task) %>
          <% else %>
            <div class="Overdue">Overdue</div>
          <% end %>
        </td>
        <td data-order="<%= task.deadline ? task.deadline.to_i : Float::INFINITY%>"><%= pretty_print_deadline(task) %></td>
        <td><%= !task.tags.empty? ? task.tags.join(", ") : "No tag" %></td>

        <td><a href="#" data-toggle="modal" data-target="#modal-edit-task" data-task-id="<%= task.id %>" class="edit-task">Edit</a> | <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<div class="show-page"><%= render 'form', task: @task %></div>

app/views/tasks/index.html.erb
<div id="notifications" style="display: none;">
	<p id="notice"><%= notice %></p>
	<p id="alert"><%= alert %></p>
</div>

<div class="modal fade" id="modal-new-task">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Create New Task</h4>
			</div>
			<div class="modal-body">
				<%= render 'form', action: 'new', task: @task %>
			</div>

		</div>
	</div>
</div>

<div class="modal fade" id="modal-show-task">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">View Task</h4>
			</div>
			<div class="modal-body">

			</div>

		</div>
	</div>
</div>

<div class="modal fade" id="modal-edit-task">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Edit Task</h4>
			</div>
			<div class="modal-body">

			</div>

		</div>
	</div>
</div>

<div class="container vertical-center" id="main">
	<h1 class="display-4" id="title-display" style="color: #f9f9f9; margin-bottom: 20px">

		  <span>
		  	Today is <%= Date::DAYNAMES[Date.today.wday] %>.

				<%= @tasks_today_ongoing.zero? ? "You've finished all the tasks!": "You've got " + pluralize(@tasks_today_ongoing, 'task') + " left today!"  %>
			</span>
		<br>
		<button type="button" class="btn btn-success btn-lg add-task" data-toggle="modal" data-target="#modal-new-task" style="margin-top: 10px;"><i class="glyphicon glyphicon-plus" style="padding-right: 5px;"></i>New Task</button>

	</h1>
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

		<!-- panel 1 - TODAY TASKS -->
		<div class="panel panel-default">
			<div class="panel-heading" role="tab" id="heading-today-tasks">
			  <h4 class="panel-title">
			    <a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-today-tasks" aria-expanded="true" aria-controls="collapse-today-tasks">
			      Today tasks
						<div style="display:inline-block; width:30px" class="badge badge-info" id="badge-noti-today">
			           <%= @tasks_today_ongoing %>
			      </div>
			    </a>
			  </h4>
			</div>
		  <div id="collapse-today-tasks" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-today-tasks">
		    <div class="panel-body">
		      <%= render 'table', tasks: @tasks_today %>
		    </div>
		  </div>
		</div>

		<!-- panel 2 - OTHER TASKS -->
		<div class="panel panel-default">
			<div class="panel-heading" role="tab" id="heading-other-tasks">
			  <h4 class="panel-title">
			    <a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-other-tasks" aria-expanded="false" aria-controls="collapse-other-tasks">
			      Other tasks
			      <div style="display:inline-block; width:30px" class="badge badge-info" id="badge-noti-other">
			           <%= @tasks_other_ongoing %>
			      </div>
			    </a>
			  </h4>
			</div>
		  <div id="collapse-other-tasks" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-other-tasks">
		    <div class="panel-body">
		      <%= render 'table', tasks: @tasks_other %>
		    </div>
		  </div>
		</div>

		<!-- panel 3 - FIND BY TAGS -->
		<div class="panel panel-default">
			<div class="panel-heading" role="tab" id="heading-find-by-tags">
			  <h4 class="panel-title">
			    <a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-find-by-tags" aria-expanded="false" aria-controls="collapse-find-by-tags">
			      Find by tags
			    </a>
			  </h4>
			</div>
		  <div id="collapse-find-by-tags" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-find-by-tags">
		    <div class="panel-body">
		      <%= select_tag "tags", options_for_select(@all_tags, ''),
		      											{prompt: 'Select a tag', class: 'form-control', style: 'width: auto; margin-bottom: 20px;'} %>
					<div id="filter-by-tag-table"></div>
		    </div>
		  </div>
		</div>

		<!-- panel 4 - UNTAGGED -->
		<div class="panel panel-default">
			<div class="panel-heading" role="tab" id="heading-untagged">
			  <h4 class="panel-title">
			    <a class="accordion-toggle" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-untagged" aria-expanded="false" aria-controls="collapse-untagged">
			      Untagged tasks
			    </a>
			  </h4>
			</div>
		  <div id="collapse-untagged" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-untagged">
				<div class="panel-body">
		      <%= render 'table', tasks: @tasks_untagged %>
		    </div>
		  </div>
		</div>



	</div><!-- panel-group -->




</div><!-- container -->

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="show-page">
  <div id="notifications" style="display: none;">
  	<p id="notice"><%= notice %></p>
  	<p id="alert"><%= alert %></p>
  </div>

  <p>
    <strong>Title:</strong>
    <%= @task.title %>
  </p>

  <p>
    <strong>Completed/On-going/Overdue:</strong>
    <%= completed_link_text(@task) %>
  </p>

  <p>
    <strong>Deadline:</strong>
    <%= @task.deadline ? @task.deadline.strftime('%B %d, %Y %H:%M') : "No deadline" %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= !@task.tags.empty? ? @task.tags.join(", ") : 'No tag' %>
  </p>

  <p>
    <strong>Notes:</strong>
    <br>
    <div style="width: 100%; border: 1px solid #333; padding: 20px;">
      <%= !@task.notes.blank? ? @task.notes.html_safe : 'No note' %>
    </div>
  </p>

</div>

app/views/tasks/toggle_completed.js.erb
$("#completed_link_<%= @task.id %>").text("<%= completed_link_text(@task) %>");
$("#completed_link_<%= @task.id %>").attr('class', '<%= completed_link_text(@task) %>');
$("#completed_link_<%= @task.id %>").parent().attr('data-order', '<%= completed_link_data_order(@task) %>');



<% if (count_today = Task.where(deadline: Date.today.beginning_of_day..Date.today.end_of_day, completed: false).where('deadline > ?', Time.now).count).zero? %>
$("#title-display>span").text("Today is <%= Date::DAYNAMES[Date.today.wday] %>. You've finished all the tasks!");
<% else %>
$("#title-display>span").text("Today is <%= Date::DAYNAMES[Date.today.wday] %>. You've got <%= pluralize(count_today, 'task') %> left today!");
<% end %>

$('#badge-noti-today').text('<%= count_today %>');
$('#badge-noti-other').text('<%= count_other = Task.where.not(deadline: Date.today.beginning_of_day..Date.today.end_of_day).where("deadline > ?", DateTime.now).or(Task.where(deadline: nil)).where(completed: false).count %>');

app/views/welcome/index.html.erb
Hello world